/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "background": "#fdf8f8",
        "surface": "#fdf8f8",
        "surface-container": "#f1edec",
        "surface-container-low": "#f7f3f2",
        "surface-container-high": "#ebe7e7",
        "surface-container-highest": "#e5e2e1",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#ddd9d8",
        "surface-variant": "#e5e2e1",
        "primary": "#161717",
        "primary-container": "#2b2b2b",
        "on-primary": "#ffffff",
        "on-primary-container": "#939292",
        "inverse-primary": "#c8c6c5",
        "secondary": "#785a06",
        "secondary-container": "#ffd57a",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#795a06",
        "tertiary": "#171715",
        "tertiary-container": "#2c2b29",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#95928f",
        "on-surface": "#1c1b1b",
        "on-surface-variant": "#444748",
        "on-background": "#1c1b1b",
        "inverse-surface": "#313030",
        "inverse-on-surface": "#f4f0ef",
        "outline": "#747878",
        "outline-variant": "#c4c7c7",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "luxury-gold": "#C9A34E",
      },
      fontFamily: {
        "display": ["'Playfair Display'", "serif"],
        "body": ["'Inter'", "sans-serif"],
      },
    },
  },
  plugins: [],
}
